version: '3.8'

services:
  app:
    build: .
    container_name: express_app
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:3000
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["nodemon", "--inspect=0.0.0.0:9229", "server.js"]
    restart: unless-stopped

  worker:
    build: .
    container_name: queue_worker
    depends_on:
      - redis
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:3000  
    ports:
      - "9230:9230"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["nodemon", "--inspect=0.0.0.0:9230", "worker/index.js"]
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: unless-stopped

volumes:
  mongodb_data:
